# Generated by Django 2.2.6 on 2019-10-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_writer', models.CharField(max_length=30)),
                ('comment_text', models.TextField(max_length=500, verbose_name='댓글내용')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
